### PR TITLE
Use FastAPI's built in jsonable_encoder

### PR DESCRIPTION
**Pull request by rushilsrivastava**

### CODE REVIEW

**Comment by shershen08** [comment]
is this one related to issues I had with my code -  https://github.com/long2ice/fastapi-cache/issues/6 ?
@rushilsrivastava

**Comment by rushilsrivastava** [comment]
Yes, this will fix the issue you had in #6. This issue occurs because you are trying to send a response with a Pydantic model that the current encoder doesn't know how to encode. The built in fastapi encoder already handles this and you can create a custom Coder in the meantime to work around that.

**Comment by long2ice** [comment]
Is it support decimal? for that we can just use it.

**Comment by rushilsrivastava** [comment]
Circling back on this, I don't believe that Decimal is supported (implementation [here](https://github.com/tiangolo/fastapi/blob/master/fastapi/encoders.py#L28)). In terms of simplicity though, would it be better for those that use Decimal to create a custom encoder?

**Comment by heliumbrain** [comment]
Any news on this? I'm currently getting the same problem as described in #6. If this will not be closed, any good examples on how to create a custom encoder? Would grealy appreciate it.

**Comment by rushilsrivastava** [comment]
> Any news on this? I'm currently getting the same problem as described in #6. If this will not be closed, any good examples on how to create a custom encoder? Would grealy appreciate it.

Until this gets merged you can use the following:

```
class JSONEncoder(json.JSONEncoder):
    """JSON Encoder for Redis caching."""

    def default(self, obj: Any) -> dict:
        """Default method to encode."""
        if isinstance(obj, Session):
            return {"db": "Session"}
        else:
            return jsonable_encoder(obj)


class JSONCoder(Coder):
    """JSONCoder for FastAPI_Cache using `jsonable_encoder`."""

    @classmethod
    def encode(cls, value: Any) -> str:
        """Encode an object into a string."""
        return json.dumps(value, cls=JSONEncoder)

    @classmethod
    def decode(cls, value: str) -> dict:
        """Decode a string into a dictionary."""
        return json.loads(value)
```

You can then call it as such:

```
@app.get("/test")
@cache(namespace="test", expire=60, coder=JSONCoder)
async def test():
    return "test"
```

**Comment by heliumbrain** [comment]
> > Any news on this? I'm currently getting the same problem as described in #6. If this will not be closed, any good examples on how to create a custom encoder? Would grealy appreciate it.
> 
> Until this gets merged you can use the following:
> 
> ```python
> class JSONEncoder(json.JSONEncoder):
>     """JSON Encoder for Redis caching."""
> 
>     def default(self, obj: Any) -> dict:
>         """Default method to encode."""
>         return jsonable_encoder(obj)
> 
> 
> class JSONCoder(Coder):
>     """JSONCoder for FastAPI_Cache using `jsonable_encoder`."""
> 
>     @classmethod
>     def encode(cls, value: Any) -> str:
>         """Encode an object into a string."""
>         return json.dumps(value, cls=JSONEncoder)
> 
>     @classmethod
>     def decode(cls, value: str) -> dict:
>         """Decode a string into a dictionary."""
>         return json.loads(value)
> ```
> 
> You can then call it as such:
> 
> ```python
> @app.get("/test")
> @cache(namespace="test", expire=60, coder=JSONCoder)
> async def test():
>     return "test"
> ```

That works great, thanks a lot for your help! 👍

**Comment by GabrieleCalarota** [comment]
When will this feature be released in a new version of the package?

**Pull request merged**
