### PR TITLE
Support python3.12

### PR DESCRIPTION
**Pull request by mkdir700**
closes: #392

### CODE REVIEW

**Comment by mkdir700** [comment]
@long2ice Workflow needs to be modified to support running CI on Python 3.12

**Comment by Wolfhound905** [comment]
I do not agree with just changing to import to v1, a proper transition should be made to the current version on Pydantic.

**Comment by mkdir700** [comment]
Thank you, I understand this, but this PR is to support Python3.12, not to support Pydanic v2.

Regarding the support for Pydantic V2, I think this should be opened as a separate issue.

**Comment by vicchi** [comment]
@mkdir700 @Wolfhound905 Support for Python 3.12 will be part of the upcoming `0.3.0` release, see #462 

Right now, the package dependencies specify either Pydantic `v1` _or_ `v2`.

The `1.0.0` release will deprecate Pydantic v1 support entirely, see #463 

For now I'm going to close this PR in favour of #463, not least because it changes current Pydantic behaviour at the same time as supporting Python 3.12. Feel free to re-open if you disagree.

**Pull request closed without merging**
